### PR TITLE
Add post create data set

### PR DESCRIPTION
**Pull request by jcbashdown**
Relies on 

https://github.com/alphagov/stagecraft/pull/288

### CODE REVIEW

**Comment by tombooth** [comment]
pep-it.sh ignores a bunch of directories

**Comment by tombooth** [comment]
Want to bump the version so it gets release?

**Comment by jcbashdown** [comment]
This pr or a separate one? 

Spotted a small bug in the stagcraft side testing with curl. Fixing now.

**Comment by tombooth** [comment]
I'd just do it at the end of this PR, it will relate that bump to the code changes.

**Comment by jcbashdown** [comment]
Will do

**Comment by jcbashdown** [comment]
@tombooth This is also ready.

**Pull request merged**
