### PR TITLE
Wheels, tox, pytest and better linting

### PR DESCRIPTION
**Pull request by richardasaurus**
- Changes package to use [`tox`](https://tox.readthedocs.org/en/latest/) for simpler testing. (see readme update for how to run tests).

- [pytest](http://pytest.org/latest/) instead of nose, for cleaner assert statements.

- [wheels](http://pythonwheels.com/) format distribution capabilities since that's the new standard.

- Stricter pep8 style linting through additions of `flake8`, `pep8-naming` and `mccabe` in tox.ini.

### CODE REVIEW

**Comment by richardasaurus** [comment]
Code review anyone? Perhaps @tombooth ?

I assume her majesty allows anyone to submit a PR :+1:

**Comment by alicebartlett** [comment]
Hi @richardasaurus! Thanks for your PR. We code in the open so people can see what we're up to and suggest improvements, so this type of thing is welcome across all our repos.

You pull request sparked some interesting conversations among the team. We've decided to stay with nose for now but if we decide to revisit the situation in the future this will serve as an excellent reference.

**Comment by richardasaurus** [comment]
I can understand you may want to use nose over pytest, but why close the entire pull request? 

tox adds a whole testing framework and removes a bunch of needless bash scripts replacing them with a single command to test against multiple python or pypy versions should you wish. (["concentrate on the irreducible core"](https://www.gov.uk/design-principles#second)).

the advantages of wheels are listed here: http://pythonwheels.com/

Would you like me to update this PR to exclude the nose related changes?

**Comment by alicebartlett** [comment]
This isn't a case of one thing being better than the other, it's that what we have works for us and is well understood by all team members. Our current set-up benefits from being the same across all of our python repos meaning knowledge from one repo is transferable to another. 

We've written more about how we choose technologies and why switching them should be considered non-trivial here if you're interested: https://www.gov.uk/service-manual/making-software/choosing-technology.html#cost

**Comment by richardasaurus** [comment]
I'd have to disagree, tox is clearly better, which is why it's the standard across most popular open source python packages. 
And if developers cannot read a README file for instructions on how to run the unit tests for a given package that's a different issue altogether.

**Comment by tombooth** [comment]
Hi @richardasaurus, thanks for the pointers as to how we would set these tools up for our client library.

We use a common set of libraries and tools across our Python applications and libraries, although we would like benefit from moving to different set there is a pragmatism call to be made. At the moment we are heads down in delivering the backend applications to fully realise the power of the Performance Platform and I can't justify the time to go through and bring parity across our stack, as the areas address have not been pain points for us.

We definitely appreciate the guide to tooling that could help move us faster and I am sure we will find the time to adopt these into our stack as the seem like sensible changes.

**Pull request closed without merging**
